#!/usr/bin/env python3
"""Tests for scripts/friction-report.py.

Run with: python3 -m unittest discover tests

The friction report is a read-only analyzer over what Claude Code persists in
~/.claude/projects/**/*.jsonl. These tests build synthetic transcript files and
assert the report's detection, joins and rankings — never touching a real
transcript.

Signature fidelity: the nudge and Stop-block fixtures are generated by calling
the hooks' own message builders, and the event names come from the watcher's
own `report_header` call sites — not from hand-copied strings. A wording change
that broke a detector therefore fails these tests instead of silently reporting
real usage as zero.

Fixture rule (as elsewhere in this suite): synthetic PR numbers and paths only.
"""
import io
import json
import os
import re
import subprocess
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from importlib import util
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCRIPT = REPO / "scripts" / "friction-report.py"
HOOK = REPO / "scripts" / "pr-sentinel-hook.py"
STOP_HOOK = REPO / "scripts" / "pr-sentinel-stop-hook.py"
GUARD = REPO / "scripts" / "pr-sentinel-guard.py"
WATCHER = REPO / "scripts" / "pr-sentinel-watch.sh"

# A synthetic plugin root, so the generated nudge names a watcher path with the
# same shape as a real install without pointing at one.
PLUGIN_ROOT = "/synthetic/plugins/pr-sentinel"


def _load(path, name):
    """Filenames have dashes, so import by path."""
    spec = util.spec_from_file_location(name, path)
    mod = util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


fr = _load(SCRIPT, "friction_report")
hook = _load(HOOK, "pr_sentinel_hook")
stop_hook = _load(STOP_HOOK, "pr_sentinel_stop_hook")
guard = _load(GUARD, "pr_sentinel_guard")
overlap = _load(REPO / "scripts" / "pr_sentinel_overlap.py", "pr_sentinel_overlap")

# Every reason the guard hands to `permissionDecisionReason`, and the real text
# each one produces. Generated from the guard's own builders, so a reworded
# branch fails the classification tests instead of silently reporting zero.
GUARD_BUILDERS = {
    "build_allow_reason": lambda: guard.build_allow_reason(),
    "build_reason": lambda: guard.build_reason("gh_run_watch"),
    "build_duplicate_reason": lambda: guard.build_duplicate_reason(
        "41", ["task-1"]),
    "overlap.build_reason": lambda: overlap.build_reason(
        [("41", ["src/synthetic.py"], True)]),
}

GUARD_CATEGORIES = {
    "build_allow_reason": "auto-allow",
    "build_reason": "poll",
    "build_duplicate_reason": "duplicate",
    "overlap.build_reason": "overlap",
}


def guard_reason_builders():
    """Every builder named at a `permissionDecisionReason` call site."""
    text = GUARD.read_text(encoding="utf-8")
    return set(re.findall(r"'permissionDecisionReason':\s*([\w.]+)\(", text))

def _signatures():
    """The real nudge and Stop-block texts, from the hooks' own builders.

    Both read CLAUDE_PLUGIN_ROOT at call time, so it is set only across these
    calls and restored afterwards — a module-scope assignment would leak into
    the sibling suites, which assert on their own plugin root.
    """
    saved = os.environ.get("CLAUDE_PLUGIN_ROOT")
    os.environ["CLAUDE_PLUGIN_ROOT"] = PLUGIN_ROOT
    try:
        return (hook.build_context("pr_create", "41"),
                hook.build_context("push", "41"),
                hook.build_context("push", None),
                stop_hook.build_reason(["41"]))
    finally:
        if saved is None:
            os.environ.pop("CLAUDE_PLUGIN_ROOT", None)
        else:
            os.environ["CLAUDE_PLUGIN_ROOT"] = saved


NUDGE_CREATE, NUDGE_PUSH, NUDGE_PUSH_UNRESOLVED, STOP_REASON = _signatures()

# Every remaining string a hook hands the model or the human, beside the guard's
# four reasons above: both PostToolUse nudges, the Stop block, and the Stop
# hook's non-blocking notice. Keyed by module, so the two `build_reason`s stay
# apart. Each entry yields every text its builder can produce.
HOOK_MESSAGES = {
    "hook.build_context": lambda: (NUDGE_CREATE, NUDGE_PUSH,
                                   NUDGE_PUSH_UNRESOLVED),
    "hook.build_live_context": lambda: (
        hook.build_live_context("41", ["task-1"]),),
    "stop_hook.build_reason": lambda: (STOP_REASON,),
    "stop_hook.build_warning": lambda: (
        stop_hook.build_warning({"41": "check_failure"}),),
}


def hook_message_builders():
    """Every builder feeding an agent-facing field in the two non-guard hooks.

    The Stop hook names its builder at the assignment. The PostToolUse hook
    picks one into `context` a few lines above its single emission site, so the
    branch is read off that assignment rather than off the `print`.
    """
    nudges = re.findall(r"\bcontext = (\w+)\(", HOOK.read_text(encoding="utf-8"))
    stop = re.findall(r"out\['(?:reason|systemMessage)'\] = (\w+)\(",
                      STOP_HOOK.read_text(encoding="utf-8"))
    return {"hook." + n for n in nudges} | {"stop_hook." + n for n in stop}


WATCHER_PATH = os.path.join(PLUGIN_ROOT, "scripts", "pr-sentinel-watch.sh")


def watcher_event_names():
    """Every event the watcher emits, from its own `report_header` call sites."""
    text = WATCHER.read_text(encoding="utf-8")
    return set(re.findall(r"^\s*report_header\s+([a-z_]+)\s*$", text, re.M))


def report_text(event, pr, extra="State: OPEN"):
    """A watcher report as it reaches the transcript."""
    return "PR-SENTINEL EVENT: %s\nPR: %s\n%s" % (event, pr, extra)


def numbered(text):
    """The same text as the Read tool renders it — `<lineno>\\t` prefixes."""
    return "\n".join("%6d\t%s" % (i, l)
                     for i, l in enumerate(text.split("\n"), 1))


# --- transcript record builders ---------------------------------------------

TS = "2026-08-18T12:00:00.000Z"
CWD = "/synthetic/workspace/demo-repo"


def rec_nudge(context, ts=TS, cwd=CWD, tool_use_id="toolu_nudge"):
    stdout = json.dumps({"hookSpecificOutput": {
        "hookEventName": "PostToolUse", "additionalContext": context}})
    return {"type": "attachment", "timestamp": ts, "cwd": cwd,
            "attachment": {"type": "hook_success",
                           "hookName": "PostToolUse:Bash",
                           "toolUseID": tool_use_id, "stdout": stdout}}


def rec_launch(pr, background=True, ts=TS, cwd=CWD, tool_use_id="toolu_launch",
               command=None):
    cmd = command if command is not None \
        else 'bash "%s" %s' % (WATCHER_PATH, pr)
    return {"type": "assistant", "timestamp": ts, "cwd": cwd,
            "message": {"role": "assistant", "content": [
                {"type": "tool_use", "id": tool_use_id, "name": "Bash",
                 "input": {"command": cmd, "run_in_background": background}}]}}


def rec_bash(command, ts=TS, cwd=CWD, tool_use_id="toolu_bash"):
    """A Bash tool_use that is not a watcher launch."""
    return rec_launch(None, ts=ts, cwd=cwd, tool_use_id=tool_use_id,
                      command=command)


def rec_result(text, ts=TS, cwd=CWD, tool_use_id="toolu_result"):
    return {"type": "user", "timestamp": ts, "cwd": cwd,
            "message": {"role": "user", "content": [
                {"type": "tool_result", "tool_use_id": tool_use_id,
                 "content": text}]}}


def rec_guard_allow(reason=None, ts=TS, cwd=CWD, tool_use_id="toolu_guard",
                    atype="hook_success", stdout=None):
    """A PreToolUse attachment carrying the guard's verdict."""
    if stdout is None:
        stdout = json.dumps({"hookSpecificOutput": {
            "hookEventName": "PreToolUse", "permissionDecision": "allow",
            "permissionDecisionReason":
                reason if reason is not None else guard.build_allow_reason()}})
    return {"type": "attachment", "timestamp": ts, "cwd": cwd,
            "attachment": {
                "type": atype, "hookName": "PreToolUse:Bash",
                "command": 'python3 "/plugins/pr-sentinel/scripts/'
                           'pr-sentinel-guard.py"',
                "toolUseID": tool_use_id, "stdout": stdout}}


def rec_guard_deny(reason, ts=TS, cwd=CWD, tool_use_id="toolu_bash"):
    """The error a denied call hands back — the only record of a deny."""
    rec = rec_result(reason, ts=ts, cwd=cwd, tool_use_id=tool_use_id)
    rec["message"]["content"][0]["is_error"] = True
    return rec


def rec_stop_block(reason, ts=TS, cwd=CWD):
    return {"type": "system", "subtype": "stop_hook_summary", "timestamp": ts,
            "cwd": cwd, "hookCount": 1, "hookErrors": [reason]}


class TranscriptCase(unittest.TestCase):
    """Writes synthetic transcripts and runs the collector over them."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        self.addCleanup(self.tmp.cleanup)
        self._n = 0

    def write(self, records, name=None):
        self._n += 1
        proj = self.root / ("project-%d" % self._n)
        proj.mkdir(parents=True, exist_ok=True)
        path = proj / (name or "session.jsonl")
        with open(path, "w", encoding="utf-8") as fh:
            for r in records:
                fh.write(json.dumps(r) + "\n")
        return path

    def report(self, since="all", repo=""):
        cutoff = None if since == "all" else fr.parse_since(since)
        paths = sorted(str(p) for p in self.root.glob("**/*.jsonl"))
        return fr.build_report(fr.collect(paths, cutoff, repo))


# --- the watcher/report contract --------------------------------------------

class TestEventContract(unittest.TestCase):

    def test_event_kinds_cover_every_watcher_event(self):
        """A new watcher event must be classified here, or the report buckets
        it as 'unknown' and the ranking quietly loses meaning."""
        emitted = watcher_event_names()
        self.assertTrue(emitted, "no report_header call sites found — the "
                                 "signature regex has drifted from the watcher")
        missing = emitted - set(fr.EVENT_KIND)
        self.assertEqual(set(), missing,
                         "the watcher emits these and EVENT_KIND does not "
                         "classify them: %s" % sorted(missing))

    def test_event_kinds_names_no_event_the_watcher_dropped(self):
        stale = set(fr.EVENT_KIND) - watcher_event_names()
        self.assertEqual(set(), stale,
                         "EVENT_KIND classifies events the watcher no longer "
                         "emits: %s" % sorted(stale))

    def test_every_kind_has_a_hint(self):
        self.assertEqual(set(fr.EVENT_KIND.values()), set(fr.KIND_HINT))

    def test_contract_test_can_fail(self):
        """The coverage test is only worth having if a dropped classification
        actually fails it."""
        emitted = watcher_event_names()
        self.assertIn("ready", emitted)
        trimmed = dict(fr.EVENT_KIND)
        trimmed.pop("ready")
        self.assertTrue(emitted - set(trimmed))


# --- nudges ------------------------------------------------------------------

class TestNudges(TranscriptCase):

    def test_counts_create_and_push_nudges(self):
        self.write([rec_nudge(NUDGE_CREATE), rec_nudge(NUDGE_PUSH)])
        r = self.report()
        self.assertEqual(2, r["nudges_total"])
        self.assertEqual(1, r["nudges"]["create"])
        self.assertEqual(1, r["nudges"]["push"])

    def test_unresolved_push_nudge_counted_apart(self):
        """A push nudge with no PR number cannot be scored for follow-through,
        so it is reported separately rather than as an unanswered nudge."""
        self.write([rec_nudge(NUDGE_PUSH_UNRESOLVED)])
        r = self.report()
        self.assertEqual(1, r["nudges_total"])
        self.assertEqual(1, r["nudges_unresolved"])
        self.assertEqual(0, r["paired"])
        self.assertIsNone(r["follow_through"])

    def test_ignores_another_plugins_posttooluse_output(self):
        other = json.dumps({"hookSpecificOutput": {
            "hookEventName": "PostToolUse",
            "additionalContext": "other-plugin: pr-sentinel is not the author"}})
        rec = rec_nudge(NUDGE_CREATE)
        rec["attachment"]["stdout"] = other
        self.write([rec])
        self.assertEqual(0, self.report()["nudges_total"])

    def test_ignores_non_posttooluse_attachment(self):
        rec = rec_nudge(NUDGE_CREATE)
        rec["attachment"]["hookName"] = "PreToolUse:Bash"
        self.write([rec])
        self.assertEqual(0, self.report()["nudges_total"])


# --- launches ----------------------------------------------------------------

class TestLaunches(TranscriptCase):

    def test_counts_a_real_launch(self):
        self.write([rec_launch("41")])
        r = self.report()
        self.assertEqual(1, r["launches"])
        self.assertEqual(0, r["launches_foreground"])

    def test_flags_a_foreground_launch(self):
        self.write([rec_launch("41", background=False)])
        r = self.report()
        self.assertEqual(1, r["launches"])
        self.assertEqual(1, r["launches_foreground"])

    def test_mentioning_the_script_is_not_a_launch(self):
        """The defect that made the first draft report 2558 launches where 2372
        happened: every grep, cat, find and heredoc naming the script counted."""
        mentions = [
            'grep -n "WATCH_UNTIL" %s' % WATCHER_PATH,
            'git diff scripts/pr-sentinel-watch.sh',
            'find ~/.claude -name pr-sentinel-watch.sh',
            'cat > tests/test_watcher.py <<EOF\npr-sentinel-watch.sh\nEOF',
            'shellcheck scripts/pr-sentinel-watch.sh',
        ]
        self.write([rec_bash(c, tool_use_id="t%d" % i)
                    for i, c in enumerate(mentions)])
        self.assertEqual(0, self.report()["launches"])

    def test_launch_survives_a_cd_prefix_and_redirect(self):
        self.write([rec_launch(
            "41", command='cd /synthetic/repo && bash "%s" 41 > /dev/null 2>&1'
                          % WATCHER_PATH)])
        self.assertEqual(1, self.report()["launches"])

    def test_launch_command_from_the_nudge_is_recognised(self):
        """The nudge prints the exact command to run; whatever it prints must
        parse as a launch, or follow-through reads as zero."""
        m = re.search(r'^\s*(bash "[^"]+" \S+)\s*$', NUDGE_CREATE, re.M)
        self.assertIsNotNone(m, "the nudge no longer prints a bash command")
        self.write([rec_launch("41", command=m.group(1))])
        self.assertEqual(1, self.report()["launches"])


# --- events ------------------------------------------------------------------

class TestEvents(TranscriptCase):

    def test_counts_a_plain_report(self):
        self.write([rec_result(report_text("check_failure", "41"))])
        r = self.report()
        self.assertEqual(1, r["events_total"])
        self.assertEqual(1, r["events"]["check_failure"])
        self.assertEqual(1, r["kinds"]["work"])

    def test_counts_a_line_numbered_report(self):
        """A backgrounded watcher's report reaches the session as a task-output
        file, and a Read of it arrives line-numbered. Missing this shape drops
        most real events."""
        self.write([rec_result(numbered(report_text("ready", "41")))])
        r = self.report()
        self.assertEqual(1, r["events_total"])
        self.assertEqual(1, r["events"]["ready"])

    def test_report_after_watcher_warnings_still_counts(self):
        text = ("pr-sentinel-watch: WARNING: gh query failed transiently\n"
                + report_text("conflict", "41"))
        self.write([rec_result(numbered(text))])
        self.assertEqual(1, self.report()["events"]["conflict"])

    def test_multiple_reports_in_one_output_file(self):
        """A non-exiting notice and the final event share an output file."""
        text = (report_text("ready_watching", "41") + "\n"
                + report_text("conflict", "41"))
        self.write([rec_result(text)])
        r = self.report()
        self.assertEqual(1, r["events"]["ready_watching"])
        self.assertEqual(1, r["events"]["conflict"])

    def test_header_without_a_pr_line_is_not_a_report(self):
        """The watcher's own source reads `report_header` / `$1`; requiring the
        PR line is what keeps a source read from counting as usage."""
        self.write([rec_result('echo "PR-SENTINEL EVENT: $1"\necho "PR: ${PR}"')])
        self.assertEqual(0, self.report()["events_total"])

    def test_marker_inside_a_test_file_is_not_a_report(self):
        """An assertion naming the marker has no `PR:` line under it."""
        source = ('import unittest\n'
                  '    self.assertIn("PR-SENTINEL EVENT: ready", out)\n'
                  '    self.assertIn("PR: 41", out)\n')
        self.write([rec_result(numbered(source))])
        self.assertEqual(0, self.report()["events_total"])

    def test_marker_not_at_line_start_is_not_a_report(self):
        """The case the start-anchor alone defends against: a fixture that
        assigns a whole report to a variable puts the header mid-line, with a
        clean `PR:` line directly under it. The PR-line requirement cannot
        reject this one, so a substring match would count it as usage."""
        source = ('out = """PR-SENTINEL EVENT: ready\n'
                  'PR: 41\n'
                  'State: OPEN"""\n')
        self.write([rec_result(numbered(source))])
        self.assertEqual(0, self.report()["events_total"])

    def test_reading_the_same_output_twice_counts_once(self):
        """352 of 2054 raw matches in the local corpus, 17%, are the same file
        read a second time."""
        text = report_text("ready", "41")
        self.write([rec_result(text, tool_use_id="a"),
                    rec_result(numbered(text), tool_use_id="b")])
        self.assertEqual(1, self.report()["events_total"])

    def test_two_distinct_runs_on_one_pr_both_count(self):
        """Dedup keys on the report body, so a genuinely different verdict for
        the same PR is not collapsed."""
        self.write([
            rec_result(report_text("check_failure", "41", "State: OPEN"),
                       tool_use_id="a"),
            rec_result(report_text("check_failure", "41", "State: REOPENED"),
                       tool_use_id="b")])
        self.assertEqual(2, self.report()["events_total"])

    def test_dedup_is_scoped_to_one_session(self):
        text = report_text("ready", "41")
        self.write([rec_result(text)])
        self.write([rec_result(text)])
        self.assertEqual(2, self.report()["events_total"])


# --- follow-through ----------------------------------------------------------

class TestFollowThrough(TranscriptCase):

    def test_nudge_answered_by_a_launch(self):
        self.write([rec_nudge(NUDGE_CREATE), rec_launch("41")])
        r = self.report()
        self.assertEqual(1, r["answered"])
        self.assertEqual(0, r["unanswered"])
        self.assertEqual(100.0, r["follow_through"])

    def test_nudge_with_no_launch_is_unanswered(self):
        self.write([rec_nudge(NUDGE_CREATE)])
        r = self.report()
        self.assertEqual(0, r["answered"])
        self.assertEqual(1, r["unanswered"])
        self.assertEqual(0.0, r["follow_through"])

    def test_a_launch_for_a_different_pr_does_not_answer(self):
        self.write([rec_nudge(NUDGE_CREATE), rec_launch("99")])
        r = self.report()
        self.assertEqual(0, r["answered"])
        self.assertEqual(1, r["unanswered"])

    def test_repeat_nudges_for_one_pr_score_once(self):
        """The hook nudges on create and again on every push; scoring each one
        would report follow-through far below what happened."""
        self.write([rec_nudge(NUDGE_CREATE), rec_nudge(NUDGE_PUSH),
                    rec_nudge(NUDGE_PUSH), rec_launch("41")])
        r = self.report()
        self.assertEqual(3, r["nudges_total"])
        self.assertEqual(1, r["paired"])
        self.assertEqual(1, r["answered"])

    def test_counts_stop_hook_backstop_blocks(self):
        self.write([rec_stop_block(STOP_REASON)])
        self.assertEqual(1, self.report()["stop_blocks"])

    def test_ignores_another_hooks_stop_block(self):
        self.write([rec_stop_block("other-guard: you are ending your turn")])
        self.assertEqual(0, self.report()["stop_blocks"])


# --- the PreToolUse guard ----------------------------------------------------

class TestGuardContract(unittest.TestCase):

    def test_guard_categories_cover_every_branch(self):
        """A new decision branch in the guard must be classified here, or the
        report buckets it as 'other' and the ranking quietly loses meaning."""
        named = guard_reason_builders()
        self.assertTrue(named, "no permissionDecisionReason call sites found — "
                               "the signature regex has drifted from the guard")
        self.assertEqual(named, set(GUARD_BUILDERS),
                         "the guard names these reason builders and this test "
                         "does not exercise them all")
        for name, expected in GUARD_CATEGORIES.items():
            self.assertEqual(expected,
                             fr.guard_category(GUARD_BUILDERS[name]()),
                             "%s no longer classifies as %s" % (name, expected))

    def test_every_category_has_a_hint(self):
        self.assertEqual(set(fr.GUARD_CATEGORY) | {"other"}, set(fr.GUARD_HINT))

    def test_an_unknown_reason_is_other(self):
        self.assertEqual("other", fr.guard_category("pr-sentinel: something "
                                                    "this report has not met"))


class TestOpenerConvention(unittest.TestCase):
    """`pr-sentinel: ` opens every string this plugin hands back, not just the
    guard's reasons — the rule `docs/DESIGN.md` states and this report's
    `DENY_TEXT` reads. A deny leaves no other trace, so a branch that reworded
    past the opener would go uncounted rather than miscounted, here and in
    foreground-guard's cross-plugin report."""

    def test_every_message_opens_with_the_plugin_name(self):
        messages = {name: (build(),) for name, build in GUARD_BUILDERS.items()}
        messages.update((name, build()) for name, build in HOOK_MESSAGES.items())
        for name, texts in sorted(messages.items()):
            for n, text in enumerate(texts):
                with self.subTest(builder=name, variant=n):
                    self.assertRegex(
                        text, fr.DENY_TEXT,
                        "%s no longer opens with the plugin name" % name)

    def test_every_hook_message_is_exercised(self):
        """The guard half rides on test_guard_categories_cover_every_branch,
        which pins GUARD_BUILDERS to the guard's own call sites. This is the
        same coverage for the other half: a new nudge or Stop-hook branch must
        land in HOOK_MESSAGES, or the opener stops being asserted for the
        channel it added — which is how a documented rule goes stale quietly."""
        named = hook_message_builders()
        self.assertTrue(named, "no agent-facing builders found — the signature "
                               "regexes have drifted from the hooks")
        self.assertEqual(named, set(HOOK_MESSAGES),
                         "the hooks feed these builders to an agent-facing "
                         "field and this test does not exercise them all")

    def test_the_opener_check_can_fail(self):
        """An anchored match and a regex that matches anything look identical
        from a green test, so prove it rejects a message without the opener.
        The second case pins the `\\A` anchor: a per-line one would accept an
        opener buried under a preamble, which is not what the report recovers."""
        self.assertNotRegex("refusing to foreground-poll CI", fr.DENY_TEXT)
        self.assertNotRegex("preamble\npr-sentinel: buried", fr.DENY_TEXT)


class TestGuardDecisions(TranscriptCase):

    def test_counts_an_auto_allow(self):
        self.write([rec_guard_allow()])
        r = self.report()
        self.assertEqual(1, r["guard_total"])
        self.assertEqual({"allow": 1}, dict(r["guard_verdicts"]))
        self.assertEqual({"auto-allow": 1}, dict(r["guard_categories"]))

    def test_counts_a_deny_from_the_error_result(self):
        """The deny leaves no attachment; only the blocked call's error."""
        self.write([rec_bash("gh run watch 9"),
                    rec_guard_deny(GUARD_BUILDERS["build_reason"]())])
        r = self.report()
        self.assertEqual({"deny": 1}, dict(r["guard_verdicts"]))
        self.assertEqual({"poll": 1}, dict(r["guard_categories"]))

    def test_deny_categories_are_distinguished(self):
        self.write([rec_bash("gh pr create"),
                    rec_guard_deny(GUARD_BUILDERS["overlap.build_reason"]())])
        self.assertEqual({"overlap": 1}, dict(self.report()["guard_categories"]))

    def test_harness_error_prefix_still_matches(self):
        self.write([rec_bash("gh run watch 9"),
                    rec_guard_deny("Error: "
                                   + GUARD_BUILDERS["build_reason"]())])
        self.assertEqual(1, self.report()["denies"])

    def test_deny_with_no_bash_call_behind_it_is_ignored(self):
        """Nothing joins it to a Bash command, so it is not this guard's."""
        self.write([rec_guard_deny(GUARD_BUILDERS["build_reason"](),
                                   tool_use_id="toolu_nothing")])
        self.assertEqual(0, self.report()["guard_total"])

    def test_a_failing_command_is_not_a_deny(self):
        self.write([rec_bash("make check"),
                    rec_guard_deny("make: *** [check] Error 1")])
        self.assertEqual(0, self.report()["guard_total"])

    def test_another_hooks_pretooluse_attachment_is_ignored(self):
        rec = rec_guard_allow()
        rec["attachment"]["command"] = 'python3 "/plugins/bash-other-guard.py"'
        self.write([rec])
        self.assertEqual(0, self.report()["guard_total"])

    def test_a_silent_attachment_is_not_a_decision(self):
        self.write([rec_guard_allow(stdout="")])
        self.assertEqual(0, self.report()["guard_total"])

    def test_a_hook_that_never_ran_is_an_error_not_an_allow(self):
        self.write([rec_guard_allow(atype="hook_non_blocking_error")])
        r = self.report()
        self.assertEqual({"error": 1}, dict(r["guard_verdicts"]))
        self.assertEqual({}, dict(r["guard_categories"]))
        self.assertEqual({"hook_non_blocking_error": 1}, dict(r["guard_errors"]))


class TestOverrides(TranscriptCase):

    def test_counts_an_inline_prefix(self):
        self.write([rec_bash('PR_SENTINEL_OVERRIDE="just this once" '
                             'gh run watch 9')])
        r = self.report()
        self.assertEqual(1, r["overrides"])
        self.assertEqual(1, r["override_commands"].most_common(1)[0][1])

    def test_counts_a_prefix_on_a_later_link(self):
        self.write([rec_bash('mkdir -p out && PR_SENTINEL_OVERRIDE=why '
                             'gh run watch 9')])
        self.assertEqual(1, self.report()["overrides"])

    def test_the_name_as_an_argument_is_not_an_override(self):
        self.write([rec_bash("echo PR_SENTINEL_OVERRIDE=why && gh pr view 41")])
        self.assertEqual(0, self.report()["overrides"])

    def test_an_empty_value_is_not_an_override(self):
        self.write([rec_bash("PR_SENTINEL_OVERRIDE= gh run watch 9")])
        self.assertEqual(0, self.report()["overrides"])

    def test_a_leading_env_assignment_is_masked(self):
        """The ranking prints a command back; a credential a session inlined
        must not come with it."""
        self.write([rec_bash('GH_TOKEN=ghp_synthetic PR_SENTINEL_OVERRIDE=why '
                             'gh run watch 9')])
        cmd = self.report()["override_commands"].most_common(1)[0][0]
        self.assertNotIn("ghp_synthetic", cmd)
        self.assertIn("GH_TOKEN=", cmd)
        self.assertIn("PR_SENTINEL_OVERRIDE=why", cmd)
        self.assertIn("gh run watch 9", cmd)

    def test_a_heredoc_body_is_not_an_override(self):
        """The guard's own docs and source name the variable in prose; a `cat`
        or `git commit` carrying that text is writing, not overriding."""
        self.write([rec_bash("git commit -F - <<'EOF'\n"
                             "docs: name the escape hatch\n\n"
                             "PR_SENTINEL_OVERRIDE=<reason> downgrades it.\n"
                             "EOF")])
        self.assertEqual(0, self.report()["overrides"])

    def test_an_override_after_a_closed_heredoc_still_counts(self):
        self.write([rec_bash("cat > f <<'EOF'\ntext\nEOF\n"
                             "PR_SENTINEL_OVERRIDE=why gh run watch 9")])
        self.assertEqual(1, self.report()["overrides"])


# --- filters and output ------------------------------------------------------

class TestFilters(TranscriptCase):

    def test_since_excludes_older_records(self):
        old = "2026-01-01T00:00:00.000Z"
        self.write([rec_launch("41", ts=old), rec_launch("42")])
        self.assertEqual(2, self.report()["launches"])
        self.assertEqual(1, self.report(since="2026-06-01")["launches"])

    def test_repo_filter_matches_cwd_substring(self):
        self.write([rec_launch("41", cwd="/synthetic/workspace/alpha"),
                    rec_launch("42", cwd="/synthetic/workspace/beta")])
        self.assertEqual(2, self.report()["launches"])
        self.assertEqual(1, self.report(repo="alpha")["launches"])

    def test_events_ranked_by_repository(self):
        self.write([rec_result(report_text("ready", "41"),
                               cwd="/synthetic/workspace/alpha"),
                    rec_result(report_text("conflict", "42"),
                               cwd="/synthetic/workspace/alpha",
                               tool_use_id="b"),
                    rec_result(report_text("ready", "43"),
                               cwd="/synthetic/workspace/beta",
                               tool_use_id="c")])
        r = self.report()
        self.assertEqual([("alpha", 2), ("beta", 1)], r["repos"].most_common())

    def test_parse_since_rejects_garbage(self):
        with self.assertRaises(SystemExit):
            fr.parse_since("last tuesday")

    def test_sessions_with_no_activity_are_not_counted(self):
        self.write([rec_bash("echo hello")])
        self.assertEqual(0, self.report()["sessions"])


class TestOutput(TranscriptCase):

    def test_text_report_names_the_headline_numbers(self):
        self.write([rec_nudge(NUDGE_CREATE), rec_launch("41"),
                    rec_result(report_text("check_failure", "41"))])
        buf = io.StringIO()
        with redirect_stdout(buf):
            fr.print_text(self.report(), 15)
        out = buf.getvalue()
        self.assertIn("Nudges fired: 1", out)
        self.assertIn("Watchers launched: 1", out)
        self.assertIn("Follow-through: 100%", out)
        self.assertIn("check_failure", out)

    def test_empty_report_says_so(self):
        buf = io.StringIO()
        with redirect_stdout(buf):
            fr.print_text(fr.build_report(fr.collect([], None, "")), 15)
        self.assertIn("No pr-sentinel activity", buf.getvalue())

    def test_json_output_is_valid_and_complete(self):
        self.write([rec_nudge(NUDGE_CREATE), rec_launch("41"),
                    rec_result(report_text("ready", "41"))])
        proc = subprocess.run(
            [sys.executable, str(SCRIPT), "--transcripts", str(self.root),
             "--since", "all", "--json"],
            capture_output=True, text=True)
        self.assertEqual(0, proc.returncode, proc.stderr)
        data = json.loads(proc.stdout)
        self.assertEqual(1, data["nudges_total"])
        self.assertEqual(1, data["launches"])
        self.assertEqual({"ready": 1}, data["events"])
        self.assertEqual(100.0, data["follow_through"])

    def test_exits_nonzero_with_no_transcripts(self):
        empty = tempfile.mkdtemp()
        proc = subprocess.run(
            [sys.executable, str(SCRIPT), "--transcripts", empty],
            capture_output=True, text=True)
        self.assertNotEqual(0, proc.returncode)


class TestRobustness(TranscriptCase):

    def test_malformed_lines_are_skipped(self):
        path = self.write([rec_launch("41")])
        with open(path, "a", encoding="utf-8") as fh:
            fh.write("not json at all\n\n{\"type\": \"user\"}\n")
        self.assertEqual(1, self.report()["launches"])

    def test_tool_result_content_as_block_list(self):
        rec = rec_result("")
        rec["message"]["content"][0]["content"] = [
            {"type": "text", "text": report_text("ready", "41")}]
        self.write([rec])
        self.assertEqual(1, self.report()["events_total"])

    def test_record_without_timestamp_is_kept(self):
        rec = rec_launch("41")
        del rec["timestamp"]
        self.write([rec])
        self.assertEqual(1, self.report(since="7d")["launches"])


if __name__ == "__main__":
    unittest.main()
